# Generated by Django 3.2 on 2021-04-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='in_stock',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
